### ISSUE TITLE
setup.py does not contain all dependencies

### ISSUE THREAD

**Issue by kflekac** [UDST/zone_model#20]
Setup.py contains:
- 'numpy >= 1.1.0',
- 'pandas >= 0.16.0',
- 'orca >= 1.3.0',
- 'urbansim >= 0.1.1',
- 'pyyaml',
- 'scikit-learn >= 0.15.0'

However the .travis.yml also contains further packages which aren't automatically installed as dependencies and cause the loading of other modules (such as variable_generators) to fail

**Comment by smmaurer** [comment]
Hi @kflekac, thanks for reporting this last year! I cleaned things up in the latest update (PR #31). Now `setup.py` is more comprehensive, and the Travis script installs from it directly. 

We're still not able to install `variable_generators` automatically, because it's only available by cloning the GitHub repository, but at least it's noted in the setup file.
